<?php require_once "includes/store.php"; ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Voyage Voyage</title>
    <link rel="stylesheet" href="css/styles.css">
    <script src="/js/code.js" defer></script>
    <link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.css">
</head>
<body>
<div class="banner">
    <div class="logocontainer"><img src="/pictures/logo.jpg" class="logoimg"></div>
    <div class="title"><h1>Voyage d'étude</h1></div>
</div>
<div class="nav">
    <div id="btnPeople" class="button selected">Personnes</div>
    <div id="btnTransport" class="button">Transport</div>
    <div id="btnHousing" class="button">Logement</div>
    <div id="btnActivities" class="button">Activités</div>
</div>
<div class="content">
    <form method="post">
        <div id="divPeople">
            <h2>Les gens</h2>
            <table>
                <thead>
                    <tr><th>Adresse</th><th>Code postal</th><th>Ville</th><th>Prénom</th><th>Nom</th><th>Numéro de portable</th><th>Prof ou élève</th></tr>
                </thead>
                <tbody>
                    <tr><td><input type="text" id="txtAddress00" name="txtAddress[00]"></td><td><input type="text" id="txtNPA00" name="txtNPA[00]"></td><td><input type="text" name="txtCity[00]" id="txtCity00"></td><td><input type="text" name="txtFirstName[00]" id="txtFirstName00"></td><td><input type="text" name="txtLastName[00]" id="txtLastName00"></td><td><input type="text" name="txtPhone[00]" id="txtPhone00"></td><td><input type="text" name="txtprof[00]" id="txtprof00"></td></tr>
                    <tr><td><input type="text" id="txtAddress01" name="txtAddress[01]"></td><td><input type="text" id="txtNPA01" name="txtNPA[01]"></td><td><input type="text" name="txtCity[01]" id="txtCity01"></td><td><input type="text" name="txtFirstName[01]" id="txtFirstName01"></td><td><input type="text" name="txtLastName[01]" id="txtLastName01"></td><td><input type="text" name="txtPhone[01]" id="txtPhone01"></td><td><input type="text" name="txtprof[01]" id="txtprof01"></td></tr>
                    <tr><td><input type="text" id="txtAddress02" name="txtAddress[02]"></td><td><input type="text" id="txtNPA02" name="txtNPA[02]"></td><td><input type="text" name="txtCity[02]" id="txtCity02"></td><td><input type="text" name="txtFirstName[02]" id="txtFirstName02"></td><td><input type="text" name="txtLastName[02]" id="txtLastName02"></td><td><input type="text" name="txtPhone[02]" id="txtPhone02"></td><td><input type="text" name="txtprof[02]" id="txtprof02"></td></tr>
                    <tr><td><input type="text" id="txtAddress03" name="txtAddress[03]"></td><td><input type="text" id="txtNPA03" name="txtNPA[03]"></td><td><input type="text" name="txtCity[03]" id="txtCity03"></td><td><input type="text" name="txtFirstName[03]" id="txtFirstName03"></td><td><input type="text" name="txtLastName[03]" id="txtLastName03"></td><td><input type="text" name="txtPhone[03]" id="txtPhone03"></td><td><input type="text" name="txtprof[03]" id="txtprof03"></td></tr>
                    <tr><td><input type="text" id="txtAddress04" name="txtAddress[04]"></td><td><input type="text" id="txtNPA04" name="txtNPA[04]"></td><td><input type="text" name="txtCity[04]" id="txtCity04"></td><td><input type="text" name="txtFirstName[04]" id="txtFirstName04"></td><td><input type="text" name="txtLastName[04]" id="txtLastName04"></td><td><input type="text" name="txtPhone[04]" id="txtPhone04"></td><td><input type="text" name="txtprof[04]" id="txtprof04"></td></tr>
                    <tr><td><input type="text" id="txtAddress05" name="txtAddress[05]"></td><td><input type="text" id="txtNPA05" name="txtNPA[05]"></td><td><input type="text" name="txtCity[05]" id="txtCity05"></td><td><input type="text" name="txtFirstName[05]" id="txtFirstName05"></td><td><input type="text" name="txtLastName[05]" id="txtLastName05"></td><td><input type="text" name="txtPhone[05]" id="txtPhone05"></td><td><input type="text" name="txtprof[05]" id="txtprof05"></td></tr>
                    <tr><td><input type="text" id="txtAddress06" name="txtAddress[06]"></td><td><input type="text" id="txtNPA06" name="txtNPA[06]"></td><td><input type="text" name="txtCity[06]" id="txtCity06"></td><td><input type="text" name="txtFirstName[06]" id="txtFirstName06"></td><td><input type="text" name="txtLastName[06]" id="txtLastName06"></td><td><input type="text" name="txtPhone[06]" id="txtPhone06"></td><td><input type="text" name="txtprof[06]" id="txtprof06"></td></tr>
                    <tr><td><input type="text" id="txtAddress07" name="txtAddress[07]"></td><td><input type="text" id="txtNPA07" name="txtNPA[07]"></td><td><input type="text" name="txtCity[07]" id="txtCity07"></td><td><input type="text" name="txtFirstName[07]" id="txtFirstName07"></td><td><input type="text" name="txtLastName[07]" id="txtLastName07"></td><td><input type="text" name="txtPhone[07]" id="txtPhone07"></td><td><input type="text" name="txtprof[07]" id="txtprof07"></td></tr>
                    <tr><td><input type="text" id="txtAddress08" name="txtAddress[08]"></td><td><input type="text" id="txtNPA08" name="txtNPA[08]"></td><td><input type="text" name="txtCity[08]" id="txtCity08"></td><td><input type="text" name="txtFirstName[08]" id="txtFirstName08"></td><td><input type="text" name="txtLastName[08]" id="txtLastName08"></td><td><input type="text" name="txtPhone[08]" id="txtPhone08"></td><td><input type="text" name="txtprof[08]" id="txtprof08"></td></tr>
                    <tr><td><input type="text" id="txtAddress09" name="txtAddress[09]"></td><td><input type="text" id="txtNPA09" name="txtNPA[09]"></td><td><input type="text" name="txtCity[09]" id="txtCity09"></td><td><input type="text" name="txtFirstName[09]" id="txtFirstName09"></td><td><input type="text" name="txtLastName[09]" id="txtLastName09"></td><td><input type="text" name="txtPhone[09]" id="txtPhone09"></td><td><input type="text" name="txtprof[09]" id="txtprof09"></td></tr>
                    <tr><td><input type="text" id="txtAddress10" name="txtAddress[10]"></td><td><input type="text" id="txtNPA10" name="txtNPA[10]"></td><td><input type="text" name="txtCity[10]" id="txtCity10"></td><td><input type="text" name="txtFirstName[10]" id="txtFirstName10"></td><td><input type="text" name="txtLastName[10]" id="txtLastName10"></td><td><input type="text" name="txtPhone[10]" id="txtPhone10"></td><td><input type="text" name="txtprof[10]" id="txtprof10"></td></tr>
                    <tr><td><input type="text" id="txtAddress11" name="txtAddress[11]"></td><td><input type="text" id="txtNPA11" name="txtNPA[11]"></td><td><input type="text" name="txtCity[11]" id="txtCity11"></td><td><input type="text" name="txtFirstName[11]" id="txtFirstName11"></td><td><input type="text" name="txtLastName[11]" id="txtLastName11"></td><td><input type="text" name="txtPhone[11]" id="txtPhone11"></td><td><input type="text" name="txtprof[11]" id="txtprof11"></td></tr>
                    <tr><td><input type="text" id="txtAddress12" name="txtAddress[12]"></td><td><input type="text" id="txtNPA12" name="txtNPA[12]"></td><td><input type="text" name="txtCity[12]" id="txtCity12"></td><td><input type="text" name="txtFirstName[12]" id="txtFirstName12"></td><td><input type="text" name="txtLastName[12]" id="txtLastName12"></td><td><input type="text" name="txtPhone[12]" id="txtPhone12"></td><td><input type="text" name="txtprof[12]" id="txtprof12"></td></tr>
                    <tr><td><input type="text" id="txtAddress13" name="txtAddress[13]"></td><td><input type="text" id="txtNPA13" name="txtNPA[13]"></td><td><input type="text" name="txtCity[13]" id="txtCity13"></td><td><input type="text" name="txtFirstName[13]" id="txtFirstName13"></td><td><input type="text" name="txtLastName[13]" id="txtLastName13"></td><td><input type="text" name="txtPhone[13]" id="txtPhone13"></td><td><input type="text" name="txtprof[13]" id="txtprof13"></td></tr>
                    <tr><td><input type="text" id="txtAddress14" name="txtAddress[14]"></td><td><input type="text" id="txtNPA14" name="txtNPA[14]"></td><td><input type="text" name="txtCity[14]" id="txtCity14"></td><td><input type="text" name="txtFirstName[14]" id="txtFirstName14"></td><td><input type="text" name="txtLastName[14]" id="txtLastName14"></td><td><input type="text" name="txtPhone[14]" id="txtPhone14"></td><td><input type="text" name="txtprof[14]" id="txtprof14"></td></tr>
                    <tr><td><input type="text" id="txtAddress15" name="txtAddress[15]"></td><td><input type="text" id="txtNPA15" name="txtNPA[15]"></td><td><input type="text" name="txtCity[15]" id="txtCity15"></td><td><input type="text" name="txtFirstName[15]" id="txtFirstName15"></td><td><input type="text" name="txtLastName[15]" id="txtLastName15"></td><td><input type="text" name="txtPhone[15]" id="txtPhone15"></td><td><input type="text" name="txtprof[15]" id="txtprof15"></td></tr>
                    <tr><td><input type="text" id="txtAddress16" name="txtAddress[16]"></td><td><input type="text" id="txtNPA16" name="txtNPA[16]"></td><td><input type="text" name="txtCity[16]" id="txtCity16"></td><td><input type="text" name="txtFirstName[16]" id="txtFirstName16"></td><td><input type="text" name="txtLastName[16]" id="txtLastName16"></td><td><input type="text" name="txtPhone[16]" id="txtPhone16"></td><td><input type="text" name="txtprof[16]" id="txtprof16"></td></tr>
                    <tr><td><input type="text" id="txtAddress17" name="txtAddress[17]"></td><td><input type="text" id="txtNPA17" name="txtNPA[17]"></td><td><input type="text" name="txtCity[17]" id="txtCity17"></td><td><input type="text" name="txtFirstName[17]" id="txtFirstName17"></td><td><input type="text" name="txtLastName[17]" id="txtLastName17"></td><td><input type="text" name="txtPhone[17]" id="txtPhone17"></td><td><input type="text" name="txtprof[17]" id="txtprof17"></td></tr>
                    <tr><td><input type="text" id="txtAddress18" name="txtAddress[18]"></td><td><input type="text" id="txtNPA18" name="txtNPA[18]"></td><td><input type="text" name="txtCity[18]" id="txtCity18"></td><td><input type="text" name="txtFirstName[18]" id="txtFirstName18"></td><td><input type="text" name="txtLastName[18]" id="txtLastName18"></td><td><input type="text" name="txtPhone[18]" id="txtPhone18"></td><td><input type="text" name="txtprof[18]" id="txtprof18"></td></tr>
                    <tr><td><input type="text" id="txtAddress19" name="txtAddress[19]"></td><td><input type="text" id="txtNPA19" name="txtNPA[19]"></td><td><input type="text" name="txtCity[19]" id="txtCity19"></td><td><input type="text" name="txtFirstName[19]" id="txtFirstName19"></td><td><input type="text" name="txtLastName[19]" id="txtLastName19"></td><td><input type="text" name="txtPhone[19]" id="txtPhone19"></td><td><input type="text" name="txtprof[19]" id="txtprof19"></td></tr>
                    <tr><td><input type="text" id="txtAddress20" name="txtAddress[20]"></td><td><input type="text" id="txtNPA20" name="txtNPA[20]"></td><td><input type="text" name="txtCity[20]" id="txtCity20"></td><td><input type="text" name="txtFirstName[20]" id="txtFirstName20"></td><td><input type="text" name="txtLastName[20]" id="txtLastName20"></td><td><input type="text" name="txtPhone[20]" id="txtPhone20"></td><td><input type="text" name="txtprof[20]" id="txtprof20"></td></tr>
                    <tr><td><input type="text" id="txtAddress21" name="txtAddress[21]"></td><td><input type="text" id="txtNPA21" name="txtNPA[21]"></td><td><input type="text" name="txtCity[21]" id="txtCity21"></td><td><input type="text" name="txtFirstName[21]" id="txtFirstName21"></td><td><input type="text" name="txtLastName[21]" id="txtLastName21"></td><td><input type="text" name="txtPhone[21]" id="txtPhone21"></td><td><input type="text" name="txtprof[21]" id="txtprof21"></td></tr>
                    <tr><td><input type="text" id="txtAddress22" name="txtAddress[22]"></td><td><input type="text" id="txtNPA22" name="txtNPA[22]"></td><td><input type="text" name="txtCity[22]" id="txtCity22"></td><td><input type="text" name="txtFirstName[22]" id="txtFirstName22"></td><td><input type="text" name="txtLastName[22]" id="txtLastName22"></td><td><input type="text" name="txtPhone[22]" id="txtPhone22"></td><td><input type="text" name="txtprof[22]" id="txtprof22"></td></tr>
                    <tr><td><input type="text" id="txtAddress23" name="txtAddress[23]"></td><td><input type="text" id="txtNPA23" name="txtNPA[23]"></td><td><input type="text" name="txtCity[23]" id="txtCity23"></td><td><input type="text" name="txtFirstName[23]" id="txtFirstName23"></td><td><input type="text" name="txtLastName[23]" id="txtLastName23"></td><td><input type="text" name="txtPhone[23]" id="txtPhone23"></td><td><input type="text" name="txtprof[23]" id="txtprof23"></td></tr>
                    <tr><td><input type="text" id="txtAddress24" name="txtAddress[24]"></td><td><input type="text" id="txtNPA24" name="txtNPA[24]"></td><td><input type="text" name="txtCity[24]" id="txtCity24"></td><td><input type="text" name="txtFirstName[24]" id="txtFirstName24"></td><td><input type="text" name="txtLastName[24]" id="txtLastName24"></td><td><input type="text" name="txtPhone[24]" id="txtPhone24"></td><td><input type="text" name="txtprof[24]" id="txtprof24"></td></tr>
                    <tr><td><input type="text" id="txtAddress25" name="txtAddress[25]"></td><td><input type="text" id="txtNPA25" name="txtNPA[25]"></td><td><input type="text" name="txtCity[25]" id="txtCity25"></td><td><input type="text" name="txtFirstName[25]" id="txtFirstName25"></td><td><input type="text" name="txtLastName[25]" id="txtLastName25"></td><td><input type="text" name="txtPhone[25]" id="txtPhone25"></td><td><input type="text" name="txtprof[25]" id="txtprof25"></td></tr>
                    <tr><td><input type="text" id="txtAddress26" name="txtAddress[26]"></td><td><input type="text" id="txtNPA26" name="txtNPA[26]"></td><td><input type="text" name="txtCity[26]" id="txtCity26"></td><td><input type="text" name="txtFirstName[26]" id="txtFirstName26"></td><td><input type="text" name="txtLastName[26]" id="txtLastName26"></td><td><input type="text" name="txtPhone[26]" id="txtPhone26"></td><td><input type="text" name="txtprof[26]" id="txtprof26"></td></tr>
                    <tr><td><input type="text" id="txtAddress27" name="txtAddress[27]"></td><td><input type="text" id="txtNPA27" name="txtNPA[27]"></td><td><input type="text" name="txtCity[27]" id="txtCity27"></td><td><input type="text" name="txtFirstName[27]" id="txtFirstName27"></td><td><input type="text" name="txtLastName[27]" id="txtLastName27"></td><td><input type="text" name="txtPhone[27]" id="txtPhone27"></td><td><input type="text" name="txtprof[27]" id="txtprof27"></td></tr>
                    <tr><td><input type="text" id="txtAddress28" name="txtAddress[28]"></td><td><input type="text" id="txtNPA28" name="txtNPA[28]"></td><td><input type="text" name="txtCity[28]" id="txtCity28"></td><td><input type="text" name="txtFirstName[28]" id="txtFirstName28"></td><td><input type="text" name="txtLastName[28]" id="txtLastName28"></td><td><input type="text" name="txtPhone[28]" id="txtPhone28"></td><td><input type="text" name="txtprof[28]" id="txtprof28"></td></tr>
                    <tr><td><input type="text" id="txtAddress29" name="txtAddress[29]"></td><td><input type="text" id="txtNPA29" name="txtNPA[29]"></td><td><input type="text" name="txtCity[29]" id="txtCity29"></td><td><input type="text" name="txtFirstName[29]" id="txtFirstName29"></td><td><input type="text" name="txtLastName[29]" id="txtLastName29"></td><td><input type="text" name="txtPhone[29]" id="txtPhone29"></td><td><input type="text" name="txtprof[29]" id="txtprof29"></td></tr>
                    <tr><td><input type="text" id="txtAddress30" name="txtAddress[30]"></td><td><input type="text" id="txtNPA30" name="txtNPA[30]"></td><td><input type="text" name="txtCity[30]" id="txtCity30"></td><td><input type="text" name="txtFirstName[30]" id="txtFirstName30"></td><td><input type="text" name="txtLastName[30]" id="txtLastName30"></td><td><input type="text" name="txtPhone[30]" id="txtPhone30"></td><td><input type="text" name="txtprof[30]" id="txtprof30"></td></tr>
                    <tr><td><input type="text" id="txtAddress31" name="txtAddress[31]"></td><td><input type="text" id="txtNPA31" name="txtNPA[31]"></td><td><input type="text" name="txtCity[31]" id="txtCity31"></td><td><input type="text" name="txtFirstName[31]" id="txtFirstName31"></td><td><input type="text" name="txtLastName[31]" id="txtLastName31"></td><td><input type="text" name="txtPhone[31]" id="txtPhone31"></td><td><input type="text" name="txtprof[31]" id="txtprof31"></td></tr>
                    <tr><td><input type="text" id="txtAddress32" name="txtAddress[32]"></td><td><input type="text" id="txtNPA32" name="txtNPA[32]"></td><td><input type="text" name="txtCity[32]" id="txtCity32"></td><td><input type="text" name="txtFirstName[32]" id="txtFirstName32"></td><td><input type="text" name="txtLastName[32]" id="txtLastName32"></td><td><input type="text" name="txtPhone[32]" id="txtPhone32"></td><td><input type="text" name="txtprof[32]" id="txtprof32"></td></tr>
                    <tr><td><input type="text" id="txtAddress33" name="txtAddress[33]"></td><td><input type="text" id="txtNPA33" name="txtNPA[33]"></td><td><input type="text" name="txtCity[33]" id="txtCity33"></td><td><input type="text" name="txtFirstName[33]" id="txtFirstName33"></td><td><input type="text" name="txtLastName[33]" id="txtLastName33"></td><td><input type="text" name="txtPhone[33]" id="txtPhone33"></td><td><input type="text" name="txtprof[33]" id="txtprof33"></td></tr>
                    <tr><td><input type="text" id="txtAddress34" name="txtAddress[34]"></td><td><input type="text" id="txtNPA34" name="txtNPA[34]"></td><td><input type="text" name="txtCity[34]" id="txtCity34"></td><td><input type="text" name="txtFirstName[34]" id="txtFirstName34"></td><td><input type="text" name="txtLastName[34]" id="txtLastName34"></td><td><input type="text" name="txtPhone[34]" id="txtPhone34"></td><td><input type="text" name="txtprof[34]" id="txtprof34"></td></tr>
                    <tr><td><input type="text" id="txtAddress35" name="txtAddress[35]"></td><td><input type="text" id="txtNPA35" name="txtNPA[35]"></td><td><input type="text" name="txtCity[35]" id="txtCity35"></td><td><input type="text" name="txtFirstName[35]" id="txtFirstName35"></td><td><input type="text" name="txtLastName[35]" id="txtLastName35"></td><td><input type="text" name="txtPhone[35]" id="txtPhone35"></td><td><input type="text" name="txtprof[35]" id="txtprof35"></td></tr>
                    <tr><td><input type="text" id="txtAddress36" name="txtAddress[36]"></td><td><input type="text" id="txtNPA36" name="txtNPA[36]"></td><td><input type="text" name="txtCity[36]" id="txtCity36"></td><td><input type="text" name="txtFirstName[36]" id="txtFirstName36"></td><td><input type="text" name="txtLastName[36]" id="txtLastName36"></td><td><input type="text" name="txtPhone[36]" id="txtPhone36"></td><td><input type="text" name="txtprof[36]" id="txtprof36"></td></tr>
                    <tr><td><input type="text" id="txtAddress37" name="txtAddress[37]"></td><td><input type="text" id="txtNPA37" name="txtNPA[37]"></td><td><input type="text" name="txtCity[37]" id="txtCity37"></td><td><input type="text" name="txtFirstName[37]" id="txtFirstName37"></td><td><input type="text" name="txtLastName[37]" id="txtLastName37"></td><td><input type="text" name="txtPhone[37]" id="txtPhone37"></td><td><input type="text" name="txtprof[37]" id="txtprof37"></td></tr>
                    <tr><td><input type="text" id="txtAddress38" name="txtAddress[38]"></td><td><input type="text" id="txtNPA38" name="txtNPA[38]"></td><td><input type="text" name="txtCity[38]" id="txtCity38"></td><td><input type="text" name="txtFirstName[38]" id="txtFirstName38"></td><td><input type="text" name="txtLastName[38]" id="txtLastName38"></td><td><input type="text" name="txtPhone[38]" id="txtPhone38"></td><td><input type="text" name="txtprof[38]" id="txtprof38"></td></tr>
                    <tr><td><input type="text" id="txtAddress39" name="txtAddress[39]"></td><td><input type="text" id="txtNPA39" name="txtNPA[39]"></td><td><input type="text" name="txtCity[39]" id="txtCity39"></td><td><input type="text" name="txtFirstName[39]" id="txtFirstName39"></td><td><input type="text" name="txtLastName[39]" id="txtLastName39"></td><td><input type="text" name="txtPhone[39]" id="txtPhone39"></td><td><input type="text" name="txtprof[39]" id="txtprof39"></td></tr>
                    <tr><td><input type="text" id="txtAddress40" name="txtAddress[40]"></td><td><input type="text" id="txtNPA40" name="txtNPA[40]"></td><td><input type="text" name="txtCity[40]" id="txtCity40"></td><td><input type="text" name="txtFirstName[40]" id="txtFirstName40"></td><td><input type="text" name="txtLastName[40]" id="txtLastName40"></td><td><input type="text" name="txtPhone[40]" id="txtPhone40"></td><td><input type="text" name="txtprof[40]" id="txtprof40"></td></tr>
                    <tr><td><input type="text" id="txtAddress41" name="txtAddress[41]"></td><td><input type="text" id="txtNPA41" name="txtNPA[41]"></td><td><input type="text" name="txtCity[41]" id="txtCity41"></td><td><input type="text" name="txtFirstName[41]" id="txtFirstName41"></td><td><input type="text" name="txtLastName[41]" id="txtLastName41"></td><td><input type="text" name="txtPhone[41]" id="txtPhone41"></td><td><input type="text" name="txtprof[41]" id="txtprof41"></td></tr>
                    <tr><td><input type="text" id="txtAddress42" name="txtAddress[42]"></td><td><input type="text" id="txtNPA42" name="txtNPA[42]"></td><td><input type="text" name="txtCity[42]" id="txtCity42"></td><td><input type="text" name="txtFirstName[42]" id="txtFirstName42"></td><td><input type="text" name="txtLastName[42]" id="txtLastName42"></td><td><input type="text" name="txtPhone[42]" id="txtPhone42"></td><td><input type="text" name="txtprof[42]" id="txtprof42"></td></tr>
                    <tr><td><input type="text" id="txtAddress43" name="txtAddress[43]"></td><td><input type="text" id="txtNPA43" name="txtNPA[43]"></td><td><input type="text" name="txtCity[43]" id="txtCity43"></td><td><input type="text" name="txtFirstName[43]" id="txtFirstName43"></td><td><input type="text" name="txtLastName[43]" id="txtLastName43"></td><td><input type="text" name="txtPhone[43]" id="txtPhone43"></td><td><input type="text" name="txtprof[43]" id="txtprof43"></td></tr>
                    <tr><td><input type="text" id="txtAddress44" name="txtAddress[44]"></td><td><input type="text" id="txtNPA44" name="txtNPA[44]"></td><td><input type="text" name="txtCity[44]" id="txtCity44"></td><td><input type="text" name="txtFirstName[44]" id="txtFirstName44"></td><td><input type="text" name="txtLastName[44]" id="txtLastName44"></td><td><input type="text" name="txtPhone[44]" id="txtPhone44"></td><td><input type="text" name="txtprof[44]" id="txtprof44"></td></tr>
                    <tr><td><input type="text" id="txtAddress45" name="txtAddress[45]"></td><td><input type="text" id="txtNPA45" name="txtNPA[45]"></td><td><input type="text" name="txtCity[45]" id="txtCity45"></td><td><input type="text" name="txtFirstName[45]" id="txtFirstName45"></td><td><input type="text" name="txtLastName[45]" id="txtLastName45"></td><td><input type="text" name="txtPhone[45]" id="txtPhone45"></td><td><input type="text" name="txtprof[45]" id="txtprof45"></td></tr>
                    <tr><td><input type="text" id="txtAddress46" name="txtAddress[46]"></td><td><input type="text" id="txtNPA46" name="txtNPA[46]"></td><td><input type="text" name="txtCity[46]" id="txtCity46"></td><td><input type="text" name="txtFirstName[46]" id="txtFirstName46"></td><td><input type="text" name="txtLastName[46]" id="txtLastName46"></td><td><input type="text" name="txtPhone[46]" id="txtPhone46"></td><td><input type="text" name="txtprof[46]" id="txtprof46"></td></tr>
                    <tr><td><input type="text" id="txtAddress47" name="txtAddress[47]"></td><td><input type="text" id="txtNPA47" name="txtNPA[47]"></td><td><input type="text" name="txtCity[47]" id="txtCity47"></td><td><input type="text" name="txtFirstName[47]" id="txtFirstName47"></td><td><input type="text" name="txtLastName[47]" id="txtLastName47"></td><td><input type="text" name="txtPhone[47]" id="txtPhone47"></td><td><input type="text" name="txtprof[47]" id="txtprof47"></td></tr>
                    <tr><td><input type="text" id="txtAddress48" name="txtAddress[48]"></td><td><input type="text" id="txtNPA48" name="txtNPA[48]"></td><td><input type="text" name="txtCity[48]" id="txtCity48"></td><td><input type="text" name="txtFirstName[48]" id="txtFirstName48"></td><td><input type="text" name="txtLastName[48]" id="txtLastName48"></td><td><input type="text" name="txtPhone[48]" id="txtPhone48"></td><td><input type="text" name="txtprof[48]" id="txtprof48"></td></tr>
                    <tr><td><input type="text" id="txtAddress49" name="txtAddress[49]"></td><td><input type="text" id="txtNPA49" name="txtNPA[49]"></td><td><input type="text" name="txtCity[49]" id="txtCity49"></td><td><input type="text" name="txtFirstName[49]" id="txtFirstName49"></td><td><input type="text" name="txtLastName[49]" id="txtLastName49"></td><td><input type="text" name="txtPhone[49]" id="txtPhone49"></td><td><input type="text" name="txtprof[49]" id="txtprof49"></td></tr>
                </tbody>
            </table>
        </div>
        <div id="divTransport" class="hidden">
            <h2>Les transports</h2>
            <table>
                <thead>
                    <tr><th>Rendez-vous</th><th>Départ</th><th>Arrivée</th><th>Numéro de vol</th><th>Numéro de train</th><th>Numéro de bus</th><th>Prix</th></tr>
                </thead>
                <tbody>
                    <tr><td><input type="text" name="txtMeeting[00]" id="txtMeeting00"></td><td><input type="text" name="txtStart[00]" id="txtStart00"></td><td><input type="text" name="txtEnd[00]" id="txtEnd00"></td><td><input type="text" name="txtFlight[00]" id="txtFlight00"></td><td><input type="text" name="txtTrain[00]" id="txtTrain00"></td><td><input type="text" name="txtBus[00]" id="txtBus00"></td><td><input type="text" name="txtPrice[00]" id="txtPrice00"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[01]" id="txtMeeting01"></td><td><input type="text" name="txtStart[01]" id="txtStart01"></td><td><input type="text" name="txtEnd[01]" id="txtEnd01"></td><td><input type="text" name="txtFlight[01]" id="txtFlight01"></td><td><input type="text" name="txtTrain[01]" id="txtTrain01"></td><td><input type="text" name="txtBus[01]" id="txtBus01"></td><td><input type="text" name="txtPrice[01]" id="txtPrice01"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[02]" id="txtMeeting02"></td><td><input type="text" name="txtStart[02]" id="txtStart02"></td><td><input type="text" name="txtEnd[02]" id="txtEnd02"></td><td><input type="text" name="txtFlight[02]" id="txtFlight02"></td><td><input type="text" name="txtTrain[02]" id="txtTrain02"></td><td><input type="text" name="txtBus[02]" id="txtBus02"></td><td><input type="text" name="txtPrice[02]" id="txtPrice02"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[03]" id="txtMeeting03"></td><td><input type="text" name="txtStart[03]" id="txtStart03"></td><td><input type="text" name="txtEnd[03]" id="txtEnd03"></td><td><input type="text" name="txtFlight[03]" id="txtFlight03"></td><td><input type="text" name="txtTrain[03]" id="txtTrain03"></td><td><input type="text" name="txtBus[03]" id="txtBus03"></td><td><input type="text" name="txtPrice[03]" id="txtPrice03"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[04]" id="txtMeeting04"></td><td><input type="text" name="txtStart[04]" id="txtStart04"></td><td><input type="text" name="txtEnd[04]" id="txtEnd04"></td><td><input type="text" name="txtFlight[04]" id="txtFlight04"></td><td><input type="text" name="txtTrain[04]" id="txtTrain04"></td><td><input type="text" name="txtBus[04]" id="txtBus04"></td><td><input type="text" name="txtPrice[04]" id="txtPrice04"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[05]" id="txtMeeting05"></td><td><input type="text" name="txtStart[05]" id="txtStart05"></td><td><input type="text" name="txtEnd[05]" id="txtEnd05"></td><td><input type="text" name="txtFlight[05]" id="txtFlight05"></td><td><input type="text" name="txtTrain[05]" id="txtTrain05"></td><td><input type="text" name="txtBus[05]" id="txtBus05"></td><td><input type="text" name="txtPrice[05]" id="txtPrice05"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[06]" id="txtMeeting06"></td><td><input type="text" name="txtStart[06]" id="txtStart06"></td><td><input type="text" name="txtEnd[06]" id="txtEnd06"></td><td><input type="text" name="txtFlight[06]" id="txtFlight06"></td><td><input type="text" name="txtTrain[06]" id="txtTrain06"></td><td><input type="text" name="txtBus[06]" id="txtBus06"></td><td><input type="text" name="txtPrice[06]" id="txtPrice06"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[07]" id="txtMeeting07"></td><td><input type="text" name="txtStart[07]" id="txtStart07"></td><td><input type="text" name="txtEnd[07]" id="txtEnd07"></td><td><input type="text" name="txtFlight[07]" id="txtFlight07"></td><td><input type="text" name="txtTrain[07]" id="txtTrain07"></td><td><input type="text" name="txtBus[07]" id="txtBus07"></td><td><input type="text" name="txtPrice[07]" id="txtPrice07"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[08]" id="txtMeeting08"></td><td><input type="text" name="txtStart[08]" id="txtStart08"></td><td><input type="text" name="txtEnd[08]" id="txtEnd08"></td><td><input type="text" name="txtFlight[08]" id="txtFlight08"></td><td><input type="text" name="txtTrain[08]" id="txtTrain08"></td><td><input type="text" name="txtBus[08]" id="txtBus08"></td><td><input type="text" name="txtPrice[08]" id="txtPrice08"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[09]" id="txtMeeting09"></td><td><input type="text" name="txtStart[09]" id="txtStart09"></td><td><input type="text" name="txtEnd[09]" id="txtEnd09"></td><td><input type="text" name="txtFlight[09]" id="txtFlight09"></td><td><input type="text" name="txtTrain[09]" id="txtTrain09"></td><td><input type="text" name="txtBus[09]" id="txtBus09"></td><td><input type="text" name="txtPrice[09]" id="txtPrice09"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[10]" id="txtMeeting10"></td><td><input type="text" name="txtStart[10]" id="txtStart10"></td><td><input type="text" name="txtEnd[10]" id="txtEnd10"></td><td><input type="text" name="txtFlight[10]" id="txtFlight10"></td><td><input type="text" name="txtTrain[10]" id="txtTrain10"></td><td><input type="text" name="txtBus[10]" id="txtBus10"></td><td><input type="text" name="txtPrice[10]" id="txtPrice10"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[11]" id="txtMeeting11"></td><td><input type="text" name="txtStart[11]" id="txtStart11"></td><td><input type="text" name="txtEnd[11]" id="txtEnd11"></td><td><input type="text" name="txtFlight[11]" id="txtFlight11"></td><td><input type="text" name="txtTrain[11]" id="txtTrain11"></td><td><input type="text" name="txtBus[11]" id="txtBus11"></td><td><input type="text" name="txtPrice[11]" id="txtPrice11"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[12]" id="txtMeeting12"></td><td><input type="text" name="txtStart[12]" id="txtStart12"></td><td><input type="text" name="txtEnd[12]" id="txtEnd12"></td><td><input type="text" name="txtFlight[12]" id="txtFlight12"></td><td><input type="text" name="txtTrain[12]" id="txtTrain12"></td><td><input type="text" name="txtBus[12]" id="txtBus12"></td><td><input type="text" name="txtPrice[12]" id="txtPrice12"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[13]" id="txtMeeting13"></td><td><input type="text" name="txtStart[13]" id="txtStart13"></td><td><input type="text" name="txtEnd[13]" id="txtEnd13"></td><td><input type="text" name="txtFlight[13]" id="txtFlight13"></td><td><input type="text" name="txtTrain[13]" id="txtTrain13"></td><td><input type="text" name="txtBus[13]" id="txtBus13"></td><td><input type="text" name="txtPrice[13]" id="txtPrice13"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[14]" id="txtMeeting14"></td><td><input type="text" name="txtStart[14]" id="txtStart14"></td><td><input type="text" name="txtEnd[14]" id="txtEnd14"></td><td><input type="text" name="txtFlight[14]" id="txtFlight14"></td><td><input type="text" name="txtTrain[14]" id="txtTrain14"></td><td><input type="text" name="txtBus[14]" id="txtBus14"></td><td><input type="text" name="txtPrice[14]" id="txtPrice14"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[15]" id="txtMeeting15"></td><td><input type="text" name="txtStart[15]" id="txtStart15"></td><td><input type="text" name="txtEnd[15]" id="txtEnd15"></td><td><input type="text" name="txtFlight[15]" id="txtFlight15"></td><td><input type="text" name="txtTrain[15]" id="txtTrain15"></td><td><input type="text" name="txtBus[15]" id="txtBus15"></td><td><input type="text" name="txtPrice[15]" id="txtPrice15"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[16]" id="txtMeeting16"></td><td><input type="text" name="txtStart[16]" id="txtStart16"></td><td><input type="text" name="txtEnd[16]" id="txtEnd16"></td><td><input type="text" name="txtFlight[16]" id="txtFlight16"></td><td><input type="text" name="txtTrain[16]" id="txtTrain16"></td><td><input type="text" name="txtBus[16]" id="txtBus16"></td><td><input type="text" name="txtPrice[16]" id="txtPrice16"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[17]" id="txtMeeting17"></td><td><input type="text" name="txtStart[17]" id="txtStart17"></td><td><input type="text" name="txtEnd[17]" id="txtEnd17"></td><td><input type="text" name="txtFlight[17]" id="txtFlight17"></td><td><input type="text" name="txtTrain[17]" id="txtTrain17"></td><td><input type="text" name="txtBus[17]" id="txtBus17"></td><td><input type="text" name="txtPrice[17]" id="txtPrice17"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[18]" id="txtMeeting18"></td><td><input type="text" name="txtStart[18]" id="txtStart18"></td><td><input type="text" name="txtEnd[18]" id="txtEnd18"></td><td><input type="text" name="txtFlight[18]" id="txtFlight18"></td><td><input type="text" name="txtTrain[18]" id="txtTrain18"></td><td><input type="text" name="txtBus[18]" id="txtBus18"></td><td><input type="text" name="txtPrice[18]" id="txtPrice18"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[19]" id="txtMeeting19"></td><td><input type="text" name="txtStart[19]" id="txtStart19"></td><td><input type="text" name="txtEnd[19]" id="txtEnd19"></td><td><input type="text" name="txtFlight[19]" id="txtFlight19"></td><td><input type="text" name="txtTrain[19]" id="txtTrain19"></td><td><input type="text" name="txtBus[19]" id="txtBus19"></td><td><input type="text" name="txtPrice[19]" id="txtPrice19"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[20]" id="txtMeeting20"></td><td><input type="text" name="txtStart[20]" id="txtStart20"></td><td><input type="text" name="txtEnd[20]" id="txtEnd20"></td><td><input type="text" name="txtFlight[20]" id="txtFlight20"></td><td><input type="text" name="txtTrain[20]" id="txtTrain20"></td><td><input type="text" name="txtBus[20]" id="txtBus20"></td><td><input type="text" name="txtPrice[20]" id="txtPrice20"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[21]" id="txtMeeting21"></td><td><input type="text" name="txtStart[21]" id="txtStart21"></td><td><input type="text" name="txtEnd[21]" id="txtEnd21"></td><td><input type="text" name="txtFlight[21]" id="txtFlight21"></td><td><input type="text" name="txtTrain[21]" id="txtTrain21"></td><td><input type="text" name="txtBus[21]" id="txtBus21"></td><td><input type="text" name="txtPrice[21]" id="txtPrice21"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[22]" id="txtMeeting22"></td><td><input type="text" name="txtStart[22]" id="txtStart22"></td><td><input type="text" name="txtEnd[22]" id="txtEnd22"></td><td><input type="text" name="txtFlight[22]" id="txtFlight22"></td><td><input type="text" name="txtTrain[22]" id="txtTrain22"></td><td><input type="text" name="txtBus[22]" id="txtBus22"></td><td><input type="text" name="txtPrice[22]" id="txtPrice22"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[23]" id="txtMeeting23"></td><td><input type="text" name="txtStart[23]" id="txtStart23"></td><td><input type="text" name="txtEnd[23]" id="txtEnd23"></td><td><input type="text" name="txtFlight[23]" id="txtFlight23"></td><td><input type="text" name="txtTrain[23]" id="txtTrain23"></td><td><input type="text" name="txtBus[23]" id="txtBus23"></td><td><input type="text" name="txtPrice[23]" id="txtPrice23"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[24]" id="txtMeeting24"></td><td><input type="text" name="txtStart[24]" id="txtStart24"></td><td><input type="text" name="txtEnd[24]" id="txtEnd24"></td><td><input type="text" name="txtFlight[24]" id="txtFlight24"></td><td><input type="text" name="txtTrain[24]" id="txtTrain24"></td><td><input type="text" name="txtBus[24]" id="txtBus24"></td><td><input type="text" name="txtPrice[24]" id="txtPrice24"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[25]" id="txtMeeting25"></td><td><input type="text" name="txtStart[25]" id="txtStart25"></td><td><input type="text" name="txtEnd[25]" id="txtEnd25"></td><td><input type="text" name="txtFlight[25]" id="txtFlight25"></td><td><input type="text" name="txtTrain[25]" id="txtTrain25"></td><td><input type="text" name="txtBus[25]" id="txtBus25"></td><td><input type="text" name="txtPrice[25]" id="txtPrice25"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[26]" id="txtMeeting26"></td><td><input type="text" name="txtStart[26]" id="txtStart26"></td><td><input type="text" name="txtEnd[26]" id="txtEnd26"></td><td><input type="text" name="txtFlight[26]" id="txtFlight26"></td><td><input type="text" name="txtTrain[26]" id="txtTrain26"></td><td><input type="text" name="txtBus[26]" id="txtBus26"></td><td><input type="text" name="txtPrice[26]" id="txtPrice26"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[27]" id="txtMeeting27"></td><td><input type="text" name="txtStart[27]" id="txtStart27"></td><td><input type="text" name="txtEnd[27]" id="txtEnd27"></td><td><input type="text" name="txtFlight[27]" id="txtFlight27"></td><td><input type="text" name="txtTrain[27]" id="txtTrain27"></td><td><input type="text" name="txtBus[27]" id="txtBus27"></td><td><input type="text" name="txtPrice[27]" id="txtPrice27"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[28]" id="txtMeeting28"></td><td><input type="text" name="txtStart[28]" id="txtStart28"></td><td><input type="text" name="txtEnd[28]" id="txtEnd28"></td><td><input type="text" name="txtFlight[28]" id="txtFlight28"></td><td><input type="text" name="txtTrain[28]" id="txtTrain28"></td><td><input type="text" name="txtBus[28]" id="txtBus28"></td><td><input type="text" name="txtPrice[28]" id="txtPrice28"></td></tr>
                    <tr><td><input type="text" name="txtMeeting[29]" id="txtMeeting29"></td><td><input type="text" name="txtStart[29]" id="txtStart29"></td><td><input type="text" name="txtEnd[29]" id="txtEnd29"></td><td><input type="text" name="txtFlight[29]" id="txtFlight29"></td><td><input type="text" name="txtTrain[29]" id="txtTrain29"></td><td><input type="text" name="txtBus[29]" id="txtBus29"></td><td><input type="text" name="txtPrice[29]" id="txtPrice29"></td></tr>
                </tbody>
            </table>
        </div>
        <div id="divHousing" class="hidden">
            <h2>Le logement</h2>
            <div class="row">
                <div class="col-6">
                        <label class="col-3">Hotel</label>
                        <input type="text" name="txtHotelData[00]" id="txtHotelData00" class="col-5"><br>
                        <label class="col-3">Adresse</label>
                        <input type="text" name="txtHotelData[01]" id="txtHotelData01" class="col-5"><br>
                        <label class="col-3">NPA</label>
                        <input type="text" name="txtHotelData[02]" id="txtHotelData02" class="col-5"><br>
                        <label class="col-3">City</label>
                        <input type="text" name="txtHotelData[03]" id="txtHotelData03" class="col-5"><br>
                        <label class="col-3">Téléphone</label>
                        <input type="text" name="txtHotelData[04]" id="txtHotelData04" class="col-5"><br>
                        <label class="col-3">Email</label>
                        <input type="text" name="txtHotelData[05]" id="txtHotelData05" class="col-5"><br>
                </div>
                <div class="col-4">
                    <img src="pictures/hotel-none.png" id="imgHotel" alt="Pas d'image">
                </div>
            </div>
            <h4>Détail des chambres</h4>
            <table>
            <tr><th>Chambre</th><th>Etage</th><th>Max personnes</th><th>Occupant1</th><th>Occupant2</th><th>Occupant3</th><th>Occupant4</th></tr>
            <tr><td><input type="text" name="txtRoom[00]" id="txtRoom00"></td><td><input type="text" name="txtFloor[00]" id="txtFloor00"></td><td><input type="text" name="txtCapacity[00]" id="txtCapacity00"></td><td><input type="text" name="txtOcc1[00]" id="txtOcc100"></td><td><input type="text" name="txtOcc2[00]" id="txtOcc200"></td><td><input type="text" name="txtOcc3[00]" id="txtOcc300"></td><td><input type="text" name="txtOcc4[00]" id="txtOcc400"></td></tr>
            <tr><td><input type="text" name="txtRoom[01]" id="txtRoom01"></td><td><input type="text" name="txtFloor[01]" id="txtFloor01"></td><td><input type="text" name="txtCapacity[01]" id="txtCapacity01"></td><td><input type="text" name="txtOcc1[01]" id="txtOcc101"></td><td><input type="text" name="txtOcc2[01]" id="txtOcc201"></td><td><input type="text" name="txtOcc3[01]" id="txtOcc301"></td><td><input type="text" name="txtOcc4[01]" id="txtOcc401"></td></tr>
            <tr><td><input type="text" name="txtRoom[02]" id="txtRoom02"></td><td><input type="text" name="txtFloor[02]" id="txtFloor02"></td><td><input type="text" name="txtCapacity[02]" id="txtCapacity02"></td><td><input type="text" name="txtOcc1[02]" id="txtOcc102"></td><td><input type="text" name="txtOcc2[02]" id="txtOcc202"></td><td><input type="text" name="txtOcc3[02]" id="txtOcc302"></td><td><input type="text" name="txtOcc4[02]" id="txtOcc402"></td></tr>
            <tr><td><input type="text" name="txtRoom[03]" id="txtRoom03"></td><td><input type="text" name="txtFloor[03]" id="txtFloor03"></td><td><input type="text" name="txtCapacity[03]" id="txtCapacity03"></td><td><input type="text" name="txtOcc1[03]" id="txtOcc103"></td><td><input type="text" name="txtOcc2[03]" id="txtOcc203"></td><td><input type="text" name="txtOcc3[03]" id="txtOcc303"></td><td><input type="text" name="txtOcc4[03]" id="txtOcc403"></td></tr>
            <tr><td><input type="text" name="txtRoom[04]" id="txtRoom04"></td><td><input type="text" name="txtFloor[04]" id="txtFloor04"></td><td><input type="text" name="txtCapacity[04]" id="txtCapacity04"></td><td><input type="text" name="txtOcc1[04]" id="txtOcc104"></td><td><input type="text" name="txtOcc2[04]" id="txtOcc204"></td><td><input type="text" name="txtOcc3[04]" id="txtOcc304"></td><td><input type="text" name="txtOcc4[04]" id="txtOcc404"></td></tr>
            <tr><td><input type="text" name="txtRoom[05]" id="txtRoom05"></td><td><input type="text" name="txtFloor[05]" id="txtFloor05"></td><td><input type="text" name="txtCapacity[05]" id="txtCapacity05"></td><td><input type="text" name="txtOcc1[05]" id="txtOcc105"></td><td><input type="text" name="txtOcc2[05]" id="txtOcc205"></td><td><input type="text" name="txtOcc3[05]" id="txtOcc305"></td><td><input type="text" name="txtOcc4[05]" id="txtOcc405"></td></tr>
            <tr><td><input type="text" name="txtRoom[06]" id="txtRoom06"></td><td><input type="text" name="txtFloor[06]" id="txtFloor06"></td><td><input type="text" name="txtCapacity[06]" id="txtCapacity06"></td><td><input type="text" name="txtOcc1[06]" id="txtOcc106"></td><td><input type="text" name="txtOcc2[06]" id="txtOcc206"></td><td><input type="text" name="txtOcc3[06]" id="txtOcc306"></td><td><input type="text" name="txtOcc4[06]" id="txtOcc406"></td></tr>
            <tr><td><input type="text" name="txtRoom[07]" id="txtRoom07"></td><td><input type="text" name="txtFloor[07]" id="txtFloor07"></td><td><input type="text" name="txtCapacity[07]" id="txtCapacity07"></td><td><input type="text" name="txtOcc1[07]" id="txtOcc107"></td><td><input type="text" name="txtOcc2[07]" id="txtOcc207"></td><td><input type="text" name="txtOcc3[07]" id="txtOcc307"></td><td><input type="text" name="txtOcc4[07]" id="txtOcc407"></td></tr>
            <tr><td><input type="text" name="txtRoom[08]" id="txtRoom08"></td><td><input type="text" name="txtFloor[08]" id="txtFloor08"></td><td><input type="text" name="txtCapacity[08]" id="txtCapacity08"></td><td><input type="text" name="txtOcc1[08]" id="txtOcc108"></td><td><input type="text" name="txtOcc2[08]" id="txtOcc208"></td><td><input type="text" name="txtOcc3[08]" id="txtOcc308"></td><td><input type="text" name="txtOcc4[08]" id="txtOcc408"></td></tr>
            <tr><td><input type="text" name="txtRoom[09]" id="txtRoom09"></td><td><input type="text" name="txtFloor[09]" id="txtFloor09"></td><td><input type="text" name="txtCapacity[09]" id="txtCapacity09"></td><td><input type="text" name="txtOcc1[09]" id="txtOcc109"></td><td><input type="text" name="txtOcc2[09]" id="txtOcc209"></td><td><input type="text" name="txtOcc3[09]" id="txtOcc309"></td><td><input type="text" name="txtOcc4[09]" id="txtOcc409"></td></tr>
            <tr><td><input type="text" name="txtRoom[10]" id="txtRoom10"></td><td><input type="text" name="txtFloor[10]" id="txtFloor10"></td><td><input type="text" name="txtCapacity[10]" id="txtCapacity10"></td><td><input type="text" name="txtOcc1[10]" id="txtOcc110"></td><td><input type="text" name="txtOcc2[10]" id="txtOcc210"></td><td><input type="text" name="txtOcc3[10]" id="txtOcc310"></td><td><input type="text" name="txtOcc4[10]" id="txtOcc410"></td></tr>
            <tr><td><input type="text" name="txtRoom[11]" id="txtRoom11"></td><td><input type="text" name="txtFloor[11]" id="txtFloor11"></td><td><input type="text" name="txtCapacity[11]" id="txtCapacity11"></td><td><input type="text" name="txtOcc1[11]" id="txtOcc111"></td><td><input type="text" name="txtOcc2[11]" id="txtOcc211"></td><td><input type="text" name="txtOcc3[11]" id="txtOcc311"></td><td><input type="text" name="txtOcc4[11]" id="txtOcc411"></td></tr>
            <tr><td><input type="text" name="txtRoom[12]" id="txtRoom12"></td><td><input type="text" name="txtFloor[12]" id="txtFloor12"></td><td><input type="text" name="txtCapacity[12]" id="txtCapacity12"></td><td><input type="text" name="txtOcc1[12]" id="txtOcc112"></td><td><input type="text" name="txtOcc2[12]" id="txtOcc212"></td><td><input type="text" name="txtOcc3[12]" id="txtOcc312"></td><td><input type="text" name="txtOcc4[12]" id="txtOcc412"></td></tr>
            <tr><td><input type="text" name="txtRoom[13]" id="txtRoom13"></td><td><input type="text" name="txtFloor[13]" id="txtFloor13"></td><td><input type="text" name="txtCapacity[13]" id="txtCapacity13"></td><td><input type="text" name="txtOcc1[13]" id="txtOcc113"></td><td><input type="text" name="txtOcc2[13]" id="txtOcc213"></td><td><input type="text" name="txtOcc3[13]" id="txtOcc313"></td><td><input type="text" name="txtOcc4[13]" id="txtOcc413"></td></tr>
            <tr><td><input type="text" name="txtRoom[14]" id="txtRoom14"></td><td><input type="text" name="txtFloor[14]" id="txtFloor14"></td><td><input type="text" name="txtCapacity[14]" id="txtCapacity14"></td><td><input type="text" name="txtOcc1[14]" id="txtOcc114"></td><td><input type="text" name="txtOcc2[14]" id="txtOcc214"></td><td><input type="text" name="txtOcc3[14]" id="txtOcc314"></td><td><input type="text" name="txtOcc4[14]" id="txtOcc414"></td></tr>
            </table>
        </div>
        <div id="divActivities" class="hidden">
            <h2>Les activités sur place</h2>
            <table>
                <tr><th>Titre</th><th>Description</th><th>Date</th><th>Heure</th><th>Prix</th><th>Transport</th><th>Rendez-vous</th><th>Image</th></tr>
                <tr><td><input type="text" name="txtTitle[00]" id="txtTitle00"></td><td><textarea name="txtDesc[00]" id="txtDesc00"></textarea></td><td><input type="text" name="txtActDate[00]" id="txtActDate00"></td><td><input type="text" name="txtActTime[00]" id="txtActTime00"></td><td><input type="text" name="txtActPrice[00]" id="txtActPrice00"></td><td><input type="text" name="txtActTrsp[00]" id="txtActTrsp00"></td><td><input type="text" name="txtRDV[00]" id="txtRDV00"></td><td><input type="text" name="txtActImg[00]" id="txtActImg00"><img id="imgActImg00" class="actimg"/></td></tr>
                <tr><td><input type="text" name="txtTitle[01]" id="txtTitle01"></td><td><textarea name="txtDesc[01]" id="txtDesc01"></textarea></td><td><input type="text" name="txtActDate[01]" id="txtActDate01"></td><td><input type="text" name="txtActTime[01]" id="txtActTime01"></td><td><input type="text" name="txtActPrice[01]" id="txtActPrice01"></td><td><input type="text" name="txtActTrsp[01]" id="txtActTrsp01"></td><td><input type="text" name="txtRDV[01]" id="txtRDV01"></td><td><input type="text" name="txtActImg[01]" id="txtActImg01"><img id="imgActImg01" class="actimg"/></td></tr>
                <tr><td><input type="text" name="txtTitle[02]" id="txtTitle02"></td><td><textarea name="txtDesc[02]" id="txtDesc02"></textarea></td><td><input type="text" name="txtActDate[02]" id="txtActDate02"></td><td><input type="text" name="txtActTime[02]" id="txtActTime02"></td><td><input type="text" name="txtActPrice[02]" id="txtActPrice02"></td><td><input type="text" name="txtActTrsp[02]" id="txtActTrsp02"></td><td><input type="text" name="txtRDV[02]" id="txtRDV02"></td><td><input type="text" name="txtActImg[02]" id="txtActImg02"><img id="imgActImg02" class="actimg"/></td></tr>
                <tr><td><input type="text" name="txtTitle[03]" id="txtTitle03"></td><td><textarea name="txtDesc[03]" id="txtDesc03"></textarea></td><td><input type="text" name="txtActDate[03]" id="txtActDate03"></td><td><input type="text" name="txtActTime[03]" id="txtActTime03"></td><td><input type="text" name="txtActPrice[03]" id="txtActPrice03"></td><td><input type="text" name="txtActTrsp[03]" id="txtActTrsp03"></td><td><input type="text" name="txtRDV[03]" id="txtRDV03"></td><td><input type="text" name="txtActImg[03]" id="txtActImg03"><img id="imgActImg03" class="actimg"/></td></tr>
                <tr><td><input type="text" name="txtTitle[04]" id="txtTitle04"></td><td><textarea name="txtDesc[04]" id="txtDesc04"></textarea></td><td><input type="text" name="txtActDate[04]" id="txtActDate04"></td><td><input type="text" name="txtActTime[04]" id="txtActTime04"></td><td><input type="text" name="txtActPrice[04]" id="txtActPrice04"></td><td><input type="text" name="txtActTrsp[04]" id="txtActTrsp04"></td><td><input type="text" name="txtRDV[04]" id="txtRDV04"></td><td><input type="text" name="txtActImg[04]" id="txtActImg04"><img id="imgActImg04" class="actimg"/></td></tr>
                <tr><td><input type="text" name="txtTitle[05]" id="txtTitle05"></td><td><textarea name="txtDesc[05]" id="txtDesc05"></textarea></td><td><input type="text" name="txtActDate[05]" id="txtActDate05"></td><td><input type="text" name="txtActTime[05]" id="txtActTime05"></td><td><input type="text" name="txtActPrice[05]" id="txtActPrice05"></td><td><input type="text" name="txtActTrsp[05]" id="txtActTrsp05"></td><td><input type="text" name="txtRDV[05]" id="txtRDV05"></td><td><input type="text" name="txtActImg[05]" id="txtActImg05"><img id="imgActImg05" class="actimg"/></td></tr>
                <tr><td><input type="text" name="txtTitle[06]" id="txtTitle06"></td><td><textarea name="txtDesc[06]" id="txtDesc06"></textarea></td><td><input type="text" name="txtActDate[06]" id="txtActDate06"></td><td><input type="text" name="txtActTime[06]" id="txtActTime06"></td><td><input type="text" name="txtActPrice[06]" id="txtActPrice06"></td><td><input type="text" name="txtActTrsp[06]" id="txtActTrsp06"></td><td><input type="text" name="txtRDV[06]" id="txtRDV06"></td><td><input type="text" name="txtActImg[06]" id="txtActImg06"><img id="imgActImg06" class="actimg"/></td></tr>
                <tr><td><input type="text" name="txtTitle[07]" id="txtTitle07"></td><td><textarea name="txtDesc[07]" id="txtDesc07"></textarea></td><td><input type="text" name="txtActDate[07]" id="txtActDate07"></td><td><input type="text" name="txtActTime[07]" id="txtActTime07"></td><td><input type="text" name="txtActPrice[07]" id="txtActPrice07"></td><td><input type="text" name="txtActTrsp[07]" id="txtActTrsp07"></td><td><input type="text" name="txtRDV[07]" id="txtRDV07"></td><td><input type="text" name="txtActImg[07]" id="txtActImg07"><img id="imgActImg07" class="actimg"/></td></tr>
                <tr><td><input type="text" name="txtTitle[08]" id="txtTitle08"></td><td><textarea name="txtDesc[08]" id="txtDesc08"></textarea></td><td><input type="text" name="txtActDate[08]" id="txtActDate08"></td><td><input type="text" name="txtActTime[08]" id="txtActTime08"></td><td><input type="text" name="txtActPrice[08]" id="txtActPrice08"></td><td><input type="text" name="txtActTrsp[08]" id="txtActTrsp08"></td><td><input type="text" name="txtRDV[08]" id="txtRDV08"></td><td><input type="text" name="txtActImg[08]" id="txtActImg08"><img id="imgActImg08" class="actimg"/></td></tr>
                <tr><td><input type="text" name="txtTitle[09]" id="txtTitle09"></td><td><textarea name="txtDesc[09]" id="txtDesc09"></textarea></td><td><input type="text" name="txtActDate[09]" id="txtActDate09"></td><td><input type="text" name="txtActTime[09]" id="txtActTime09"></td><td><input type="text" name="txtActPrice[09]" id="txtActPrice09"></td><td><input type="text" name="txtActTrsp[09]" id="txtActTrsp09"></td><td><input type="text" name="txtRDV[09]" id="txtRDV09"></td><td><input type="text" name="txtActImg[09]" id="txtActImg09"><img id="imgActImg09" class="actimg"/></td></tr>
            </table>
        </div>
        <input type="submit" value="Ok" name="cmdSave"><input type="checkbox" name="showdata" title="Remise à zéro de tous les champs qui ne sont pas formatés correctement">Reset
    </form>
</div>

</body>
<script src="js/reload.js"></script>
</html>
